### ISSUE TITLE
Your top tips?

### ISSUE THREAD

**Issue by HaveAGitGat** [nfischer/ama#1]
Hi Nate!

Not sure if you're still using this but thought I'd post just in case.

A few months ago I finished my master's in electrical power engineering (my bachelors was in electrical and electronic engineering) and through both degrees I've really enjoyed the computer science/software aspects, so much so that I'd like to go into a software engineering career. I'm trying to expand my skillset to the point where I can get a junior position to get the ball rolling.

Are there any tips/books/guides etc that stood out to you on your path to your current position? Did you ever get a mentor or such?

Over the past 14 months I've written a few HTA, VBA,C#, ElectronJS, Python and MEAN applications and with such a breadth of things I could learn, I'm trying to narrow down the things that make the most difference. I passed some aptitude/technical tests for some code camps but another developer I spoke to mentioned that I wouldn't really benefit from those and my time could be much better spent. I haven't applied to any jobs yet but may do soon for some technical interview practice etc or perhaps there are some jobs near me that I'd be suited for, we shall see.

Thanks once again for your work on ShellJS!
Roy

**Comment by nfischer** [comment]
Looks like the original message was overwritten (not sure if that was intentional?)

> Hi Nate!
> 
> Not sure if you're still using this but thought I'd post just in case.

Yes, I still keep an eye on this! Sorry for the delayed response, things have been hectic lately.

> A few months ago I finished my master's in electrical power engineering (my bachelors was in electrical and electronic engineering) and through both degrees I've really enjoyed the computer science/software aspects, so much so that I'd like to go into a software engineering career. I'm trying to expand my skillset to the point where I can get a junior position to get the ball rolling.
> 
> Are there any tips/books/guides etc that stood out to you on your path to your current position? Did you ever get a mentor or such?

In terms of guides, I used Cracking the Coding Interview as a framework to study for interviews. This built on top of formal Computer Science course work (not sure if you've taken any programming courses as part of your degree). The courses I found most useful (for interviews **and** in the job) are Data Structures & Algorithms (this also taught me C++), Operating Systems, Intro to Programming Languages. I don't think anyone cares if you learn this in a university or somewhere else, as long as you know the concepts.

I recently got a formal mentor, although he and I usually talk about career trajectory and how to identify/assess skill-growing projects, rather than teaching me specific technical things.

> Over the past 14 months I've written a few HTA, VBA,C#, ElectronJS, Python and MEAN applications and with such a breadth of things I could learn, I'm trying to narrow down the things that make the most difference. I passed some aptitude/technical tests for some code camps but another developer I spoke to mentioned that I wouldn't really benefit from those and my time could be much better spent. I haven't applied to any jobs yet but may do soon for some technical interview practice etc or perhaps there are some jobs near me that I'd be suited for, we shall see.

I didn't join a code camp, but I know folks who think highly of the experience—YMMV. From what I've observed, bootcamps seem to not _quite_ be enough by themselves: you should supplement that experience with OS fundamentals and the concepts covered by the other classes I mentioned above. This is especially important for any systems-level programming or client-side software (ex. I work on both Android Framework internals and Chrome browser).

It sounds like you're developing a lot of skills. I think electron/node & python are the most applicable of those skills. Prior to Google, I did a lot of personal projects in Python and Node (I've never used electron). I think shell scripting and git/github experience have a lot of on-the-job value (but won't usually be mentioned in interviews).

> Thanks once again for your work on ShellJS!

Glad you like the module!

**Comment by HaveAGitGat** [comment]
Re-added my original comment (thought you might have forgotten about this ama but kept my issue open just in case.)

Thanks for going into so much detail! I've done a few programming modules during my degrees so I've got plenty to build on. I'll be sure to have a look into those guides/courses this summer. I've been spending a lot of time on Leetcode etc but definitely wanting to mix it up a bit more in terms of interview prep.

Much appreciated!
